// <auto-generated />
using System;
using DTO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DTO.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20221113182230_11")]
    partial class _11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Entity.Conc.Haber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Baslik")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icerik")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kategori")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kaynak")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Haberler");
                });

            modelBuilder.Entity("Entity.Conc.HaberSitesiModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("HaberSiteleri");
                });

            modelBuilder.Entity("Entity.Conc.Kategoriler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("siteName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("siteName");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("Entity.Conc.Linkler", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Check")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HaberSitesi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("linklers");
                });

            modelBuilder.Entity("Entity.Conc.Kategoriler", b =>
                {
                    b.HasOne("Entity.Conc.HaberSitesiModel", "site")
                        .WithMany("Kategoriler")
                        .HasForeignKey("siteName");

                    b.Navigation("site");
                });

            modelBuilder.Entity("Entity.Conc.HaberSitesiModel", b =>
                {
                    b.Navigation("Kategoriler");
                });
#pragma warning restore 612, 618
        }
    }
}
